server:
  port: 9090

spring:
  application:
    name: msvc-product
  data:
    mongodb:
      uri: mongodb://root:12345@localhost:27017/productDb?authSource=admin
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/