version: '3.9'

services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: userDb
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8086:80'
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=12345
    depends_on:
      - db

volumes:
  mysql-volume: